# Generated by Django 3.0 on 2020-12-29 09:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('navic_part1', '0002_auto_20201229_0858'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='selling_price',
            new_name='price',
        ),
    ]
