# Generated by Django 3.0 on 2020-12-29 09:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('navic_part1', '0003_auto_20201229_0905'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='actual_price',
        ),
    ]
