# Generated by Django 3.0 on 2021-01-03 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('navic_part1', '0004_remove_product_actual_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='mrp',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
    ]
