# Generated by Django 3.0 on 2020-12-25 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_auto_20201222_1804'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='razorpay_id',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
